Enable CONFIG_KALLSYMS_ALL in build workflow

diff --git a/.github/workflows/galaxy-a50.yml b/.github/workflows/galaxy-a50.yml
--- a/.github/workflows/galaxy-a50.yml
+++ b/.github/workflows/galaxy-a50.yml
@@ -68,13 +68,15 @@ jobs:
             --disable CONFIG_FIVE_HASH_SHA256 \
             --disable CONFIG_KDP_CRED \
             --disable CONFIG_KDP_NS \
-            --disable CONFIG_SECURITY_DEFEX_DEBUG
+            --disable CONFIG_SECURITY_DEFEX_DEBUG \
+            --enable CONFIG_KALLSYMS_ALL
           make CC=clang HOSTCC=clang HOSTCXX=clang++ AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip olddefconfig
+          grep -q "^CONFIG_KALLSYMS_ALL=y$" .config || (echo "CONFIG_KALLSYMS_ALL was not set, aborting" && exit 1)
 
       - name: Build kernel
         run: |
           set -eo pipefail
-          make CC=clang HOSTCC=clang HOSTCXX=clang++ AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip -j$(nproc) LOCALVERSION=" - $KERNEL_NAME"
+          make CC=clang HOSTCC=clang HOSTCXX=clang++ AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip -j$(nproc) LOCALVERSION="-$KERNEL_NAME"
 
       - name: Build ramdisk
         run: |
